---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: maudiblue
# description will be included in the image's metadata
description: Personal BlueBuild image with wayblue hyprland base and automated dotfiles management

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/wayblueorg/hyprland
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: scripts
        destination: /usr/local/share/scripts # copies scripts to system location
  
  # Ensure required packages are in the image before running scripts
  - type: rpm-ostree
    install:
      # Required for build-time cloning
      - git
      # Fish shell and related tools
      - fish
      - fastfetch
      # Virtualization and mobile container support
      - waydroid
      - virt-manager
      - libvirt
      - qemu-kvm
      - virt-viewer
      - lxqt-policykit
    remove:
      # Remove default browsers in favor of flatpaks
      - firefox
      - firefox-langpacks

  # Clone dotfiles into the image at build time
  - type: script
    scripts:
      - clone-dotfiles.sh

  - type: default-flatpaks
    configurations:
      - scope: user
        repo:
          # you can override the title to make inclusion of both system and user repos clearer
          title: Flathub (user)
      - notify: true
        scope: system
        repo:
          title: Flathub (system)
        install: # system flatpaks we want all users to have and not remove
          - org.gnome.Loupe
          - app.zen_browser.zen
          - com.spotify.Client
          - com.discordapp.Discord
          - com.github.tchx84.Flatseal

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
