---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: maudiblue
description: Custom Fedora Atomic image with Hyprland and workflow tools
base-image: ghcr.io/wayblueorg/hyprland
image-version: latest # latest is also supported if you want new updates ASAP

modules:
  # 1️⃣ Install system packages
  - type: rpm-ostree
    install:
      - fish
      - fastfetch
      - wlogout
      - NetworkManager-tui
      - waydroid
      - virt-manager
      - libvirt
      - qemu-kvm
      - virt-viewer
      - lxqt-policykit
      - cargo

  - type: dnf
    install:
      packages:
        - swaybg

  - type: files
    files:
      - source: system   # copies `files/system/*` (* means everything inside it) into your image's root folder `/`
        destination: /usr/share/scripts
      - source: etc
        destination: /etc

  # 3️⃣ Enable libvirtd and set up first boot
  - type: script
    scripts:
      - install_cargo_tools.sh
      
  - type: systemd
    system:
      enable:
        - firstboot.service
        - libvirtd.service
        - rpm-ostreed-automatic.timer

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add spaces or "Nerd Font" suffix.
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans

  - type: default-flatpaks
    configurations:
      - scope: user
        repo:
          # you can override the title to make inclusion of both system and user repos clearer
          title: Flathub (user)
      - notify: true
        scope: system
        repo:
          title: Flathub (system)
        install: 
          - io.github.flattool.Warehouse
          - app.zen_browser.zen
          - com.spotify.Client
          - com.github.tchx84.Flatseal
